### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by laitang2000** [jayeszee/rn-draw#1]
Hi, 
I've just downloaded your lib from npm and I get a error message on line 61 in whiteboard.js

Would love to help with this library and adapt it into a proper signature control!

**Comment by jayeszee** [comment]
Hi @laitang2000 would you mind pasting the actual error? Also, make sure you have the latest version of the version (0.0.4) which fixes that issue on the line. I'll be creating a better process for contributing to this library soon so at that time you are more than free to help contribute! Thanks!
