### ISSUE TITLE
SurfaceView should have explicit width and height set

### ISSUE THREAD

**Issue by wisteria-hill-technologies** [jayeszee/rn-draw#11]
Hi, 

I am trying to make this work, but I get this error.
SurfaceView should have explicit width and height set

Is this bug or am I doing something wrong?

Thank you

**Comment by wisteria-hill-technologies** [comment]
OK, I figured out that I need to set width and height in containerStyle in the RNDraw component or just wrap the RNDraw component in a View component (which looks better) as below:
`
<View style={{height: 350, width:350}}>
          <RNDraw
            containerStyle={{backgroundColor: 'rgba(0,0,0,0.01)'}}
            rewind={(undo) => {this._undo = undo}}
            clear={(clear) => {this._clear = clear}}
            color={'#000000'}
            strokeWidth={4}
          />
        </View>
`

**Comment by jayeszee** [comment]
Great, glad you sorted that out!
