### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by bec-smith** [jayeszee/rn-draw#4]
Hi! I was wondering if you have any examples of this project working - especially in Expo. I have this so far and I can't get it to draw.

`render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          Hello, This is a test!
        </Text>
              <Svg width="250" height="250">
               <RNDraw
                 containerStyle={styles.canvas}
                 color = {'#000000'}
                 strokeWidth = {4}
                 /> 
           </Svg> 
         <Text style={styles.paragraph}>
          Try drawing on this!
        </Text>
      
      </View>
    );
  }
}`

const styles = StyleSheet.create({
  canvas: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#BCCDD0',
    borderRadius: 4,
    borderWidth: 5,
    borderColor: 'black',
    color: '#ff0000',
    strokeWidth: '4',
  },});

**Comment by jayeszee** [comment]
Hey @becnichelesmith it seems like you don't have a opening `<VIew>` in your code! Also do you actually see the border of the canvas?

**Comment by jayeszee** [comment]
@becnichelesmith will you download 0.0.6 and let me know if that version works for you? keep in mind there are problems with flex box when a container has the style `alignItems: center`

**Comment by bec-smith** [comment]
Everything works now- thanks!

**Comment by bec-smith** [comment]
Any idea on how to add the buttons like you did in the example? Also: adding a way to save the drawing as an image would be super helpful
