### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by bec-smith** [jayeszee/rn-draw#8]
Any idea on how to add the buttons like you did in the example? I tried linking buttons to clear/rewind using this.refs but it breaks everything.

**Comment by clarksandholtz** [comment]
I'm also having trouble getting this to work.

I'm using Expo 22.0.0 in a `create-react-native-app` and I have not ejected.

```
          <RNDraw
            containerStyle={{ backgroundColor: "rgba(0,0,0,0)" }}
            color={"#000000"}
            strokeWidth={4}
            clear={clear => {
              console.log("Clear called");
              this._clear = clear;
            }}
          />
```

That `console.log("Clear called")` never gets run. Any idea why that would be happening?

**Comment by jayeszee** [comment]
@clarksandholtz hello, can you confirm that you are on the latest version of the library? it should be 0.0.6 thanks! Its working fine on my end.

**Comment by clarksandholtz** [comment]
Sorry @jayeszee, I should've updated my post earlier. I just had to update to 0.0.6 like you say and it worked! Thanks!

**Comment by jayeszee** [comment]
@becnichelesmith i don't follow.. why are you using this.refs? Please follow what @clarksandholtz posted and you should be fine.
