### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kbrandwijk** [jayeszee/rn-draw#9]
Thank you for creating this example. I was stuck with https://github.com/maticaputti/react-native-paint and the original https://github.com/brentvatne/signature-example that I couldn't get working on the latest Expo version (the strokes kept disappearing). Your implementation works likes a charm.

I used https://github.com/kevinstumpf/react-native-signature-pad before, but `takeSnapshotAsync` doesn't work with WebView on Android (only on iOS).

**Comment by jayeszee** [comment]
no problem :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
